### ISSUE TITLE
results in error 'NoneType' has no len()

### ISSUE THREAD

**Issue by karunchennuri** [blakeboswell/nlp-resume#1]
https://github.com/blakeboswell/nlp-resume/blob/89d61790d1f33ea05d1293d3096673cdedc57d77/main.py#L21

Stack Trace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karun/src/nlp-resume/main.py", line 21, in similarity
    return 1 - pipe.fit(target, None).predict(candidate)
  File "/Users/karun/anaconda/envs/nlp-resume/lib/python3.5/site-packages/sklearn/pipeline.py", line 165, in fit
    self.steps[-1][-1].fit(Xt, y, **fit_params)
  File "/Users/karun/src/nlp-resume/txtprocess.py", line 66, in fit
    indices = np.array([i for i in range(len(y)) if y[i] == 1])
TypeError: object of type 'NoneType' has no len()
```

**Comment by karunchennuri** [comment]
The main reason for this is 'cause CosineSim's fit function doesn't check for y's None value. Shouldn't we be passing 
return 1 - pipe.fit(target,candidate).predicate(candidate)

**Comment by blakeboswell** [comment]
You may be correct. 

I was able to reproduce that error.  However, I no longer have the resume data that code was built for.  I'll need to take a closer look to figure out what's going on  (i.e. is it an issue with how i'm building my new "dummy" resume data set or with the implementation).

The notebook which was built using the scikit learn data runs without issue.  (I had to reinstall nltk stopwords .. but other than that it was good).
